Controllers/StudController.cs
using First_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Client;
using First_MVC.Services;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace First_MVC.Controllers
{
    //    [AllowAnonymous] //by defult

    public class StudController : Controller
    {
        IStudentServies StudentServies;
        IDepartmentServies DepartmentServies;
        public StudController(IStudentServies _stdServ, IDepartmentServies _deptServ)
        {
            StudentServies= _stdServ;
            DepartmentServies=  _deptServ;
        }
        public IActionResult TestAjax() { 
        
        return View();
        }
       public IActionResult testPartial(int stdid) 
        {
            
            return PartialView("_StudentCard",StudentServies.getByID(stdid));
         
        }

        //remote validation
        public IActionResult Name_Exist(string Name,int id ) //must the same name of proparty 
                                                                    //علي عكس ان اي اسم عادي custon validation
        {
            Student student = StudentServies.getByName(Name);

            if (id == 0)  //add
            {
                if (student == null) //name not exist in database
                {
                    return Json(true);
                }
                else
                { ///name exist in db
                    return Json(false);
                }
            }
            else //edit
            {
                if (student == null) 
                {
                    return Json(true);//update name with new value not exist befor

                }
                else
                {
                    //object id==id parmeter true
                    if (student.Id == id)//name not change
                        return Json(true);
                    else
                        return Json(false);//chaged in name with value alread found
                }
            }
        }
        public IActionResult Add()
        {
            List<Department> departments = DepartmentServies.getAll();
            ViewData["Depts"] = departments;
            return View();
        }
        [HttpPost]
        public IActionResult SaveAdd(Student std)
        {
            if (ModelState.IsValid == true)
            {
               StudentServies.Crete(std);
                return RedirectToAction("Index");
            }
           // else if (std.Name != "ITI")
           // {
           //     ModelState.AddModelError("myName", "NAme Must Be ITI");//not relate to specific model property
           // }
            List<Department> departments = DepartmentServies.getAll();
            ViewData["Depts"] = departments;
            return View("Add", std);
        }
    //    [ActionName("SSS")] ///بدل مندها باسم edit هندها باسم sss
        public IActionResult Edit(int id)
        {

            List<Department> dept = DepartmentServies.getAll();
            ViewData["Department"] = dept;
            Student std = StudentServies.getByID(id);
            return View(std);
        }
        // [HttpPost]
        [HttpPost]
        public IActionResult  saveEdit([FromRoute]int Id , Student newStudent)
        
      {
            if (ModelState.IsValid == true)
            {

                StudentServies.Update(Id, newStudent);
                return RedirectToAction("Index");

            }
            List<Department> departments = DepartmentServies.getAll();
            ViewData["Department"] = departments;
            return View("Edit", newStudent);

        }
        public IActionResult Detalis(int id) {
            Student std = StudentServies.getByID(id);
            return View(std);
        }
        public IActionResult Delete(int id) {
            try {
               StudentServies.Delete(id);
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Exception", ex.InnerException.Message);
                return View("Detalis");
            }
            
            }
        public IActionResult getInfo()
        {
            return Content("OK");
        }
        public IActionResult Index()
        {
            return View(StudentServies.getAll());
        }

    }
}

Views/Stud/Add.cshtml
@model Student

@{
    SelectList depts;
    if (Model != null)
    {
        depts = new SelectList(ViewBag.Depts, "Id", "Name", Model.Dept);
    }
    else
    {
        depts = new SelectList(ViewBag.Depts, "Id", "Name");
    }
}
<form method="post" asp-action="SaveAdd" asp-controller="Stud">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div>
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div>
        <label asp-for="Age"></label>
        <input asp-for="Age" class="form-control" />
        <span class="text-danger" asp-validation-for="Age"></span>
    </div>
    <div>
        <label asp-for="Adress"></label>
        <input asp-for="Adress" class="form-control" />
        <span class="text-danger" asp-validation-for="Adress"></span>
    </div>
    <div>
        <label asp-for="Image"></label>
        <input asp-for="Image" class="form-control" />
        <span class="text-danger" asp-validation-for="Image"></span>
    </div>
    <div>
        <label asp-for="Dept"></label>
        <select asp-for="Dept" asp-items="depts" class="form-control">
            <option>--Depts--</option>
        </select>
        <span class="text-danger" asp-validation-for="Dept"></span>

    </div>
    <input type="submit" class="btn btn-success" value="Save" />
</form>
<br />

<a asp-action="Index" asp-controller="Stud" class="btn btn-success">back To List</a>

@section Scripts{
@*    <script src="~/lib/jquery/dist/jquery.js"></script>
*@ 
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js">
    </script>
}

Views/Stud/Detalis.cshtml
@model Student

<partial name="_StudentCard" model="@Model" />
<a class="btn btn-success"
   asp-action="Delete"
   asp-controller="Stud"
   asp-route-id="@Model.Id"
   onclick="ConfirmDelete(event)">Delete</a>

<script>
    function ConfirmDelete() {
        document.getElementById("")
        var accept = confirm("Are You Sure?");
        if (accept == false) {
            event.preventDefault();//pervent go to server
        }
    }
</script>

Views/Stud/Edit.cshtml
@*@model Student
<form action="\Stud\saveEdit\@Model.Id" method="post">
    <div>
        <label for="Name">Name</label>
        <input type="text" name="Name" id="Name" value="@Model.Name" class="form-control" />
  </div>
   <div>
       <label for="Age">Age</label>
       <input type="text" name="Age" id="Age" value="@Model.Age" class="form-control" />
  </div>
   <div>
       <label for="Address">Address</label>
        <input type="text" name="Adress" id="Adress" value="@Model.Adress" class="form-control" />
  </div>
   <div>
       <label for="Image">Image</label>
       <input type="text" name="Image" id="Image" value="@Model.Image" class="form-control" />
  </div>
   <div>
 <label for="Dept">Department</label>
        @*<input type="text" name="Dept" id="Dept" value="@Model.Dept" class="form-control" />*@
      @*  <select name="Dept" id="Dept" class="form-control">
            @foreach (var departmentItem in ViewBag.Department)
            {
                if (departmentItem.Id == Model.Dept)
                {
                    <option value="@departmentItem.Id" selected>@departmentItem.Name</option>
                }
                else
                {
                    <option value="@departmentItem.Id">@departmentItem.Name</option>
                }
            }
        </select>
    </div>
    <input type="submit" class="btn btn-sucess" value="Save" />
</form>*@
       



@*Tag Helper*@
@model Student
@{
    SelectList deptlists = new SelectList(ViewBag.Department, "Id", "Name", Model.Dept);
}
<form asp-action="saveEdit" asp-controller="Stud" asp-route-id="@Model.Id">
     <input asp-for="Id" type="hidden"  class="form-control" />
     <div>
        <label asp-for="Name"></label>
        <input asp-for="Name"  class="form-control" />
        <span class="text-danger " asp-validation-for="Name"></span>
    </div>
    <div>
       <label asp-for="Age"></label>
       <input asp-for="Age" class="form-control"/>
       <span class="text-danger" asp-validation-for="Age"></span>
    </div>
   <div>
        <label asp-for="Adress"></label>
        <input asp-for="Adress" class="form-control" />
        <span class="text-danger" asp-validation-for="Adress"></span>
  </div>
   <div>
       <label asp-for="Image"></label>
       <input asp-for="Image"  class="form-control" />
       <span class="text-danger" asp-validation-for="Image"></span>
  </div>
   <div>
        <label asp-for="Dept" ></label>
        <select asp-for="Dept" asp-items="deptlists" class="form-control">
            <option>--Depts--</option>
        </select>
        <span class="text-danger" asp-validation-for="Dept"></span>
        
    </div>
    <input type="submit" class="btn btn-success" value="Save" />
</form>
@section Scripts{
    @*<script src="~/lib/jquery/dist/jquery.js"></script>*@
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js">
    </script>
}

Views/Stud/Index.cshtml
@model List<Student>
@foreach(var item in Model){
    <partial name="_StudentCard" model="@item" />

}
<a href="\Stud\Edit\8">Edit</a>

<a asp-action="Add" asp-controller="Stud" class="btn btn-danger"> New Student</a>

Views/Stud/TestAjax.cshtml
<div style="background-color:chocolate"></div>

<input type="text" id="id" />
<input type="button" onclick="AjaxCall()" value="Show" class="btn btn-success" />
@section Scripts{
<script src="~/lib/jquery/dist/jquery.min.js"></script>

<script>
        function AjaxCall(){
            var id =$("#id").val();
            $.ajax(
                {
                    url: "/Stud/testPartial",
                    data: { "stdid": id },
                    success: function (result) {
                        $("#div1").html(result);
                    }
                }
            );
    }


</script>


}

Views/Stud/_StudentCard.cshtml
@model Student
<div class="card" style="width:400px">
    <div class="card-body">
    <h4 class="card-title">@Model.Name</h4>
    <p class="card-text">@Model.Adress</p>
        <a asp-action="Detalis" asp-controller="Stud" asp-route-id="@Model.Id" class="btn btn-primary">see your profile</a>
    </div>

    <img class="card-img-bottom" src="/images/@Model.Image" alt="Card image" style="width:100%">

</div>